In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_excel(r"C:\Users\anchsingh\Anchal Singh\Data Analysis with Python\Salary_Data.xlsx")

In [5]:
data.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [6]:
#Checking data types of each column

data.dtypes

YearsExperience    float64
Salary               int64
dtype: object

In [7]:
#Count of unique data types

data.dtypes.value_counts()

float64    1
int64      1
Name: count, dtype: int64

In [8]:
#Selecting data based on data types

# data.select_dtypes(include=None,exclude=None)

data.select_dtypes(include="float").head(5)

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [9]:
#Concise summary of dataframe

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes

In [10]:
#Unique elements of columns

np.unique(data['YearsExperience'])

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.7,  3.9,  4. ,
        4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,  7.9,  8.2,
        8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [11]:
np.unique_counts(data['YearsExperience'])

UniqueCountsResult(values=array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.7,  3.9,  4. ,
        4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,  7.9,  8.2,
        8.7,  9. ,  9.5,  9.6, 10.3, 10.5]), counts=array([1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]))

In [12]:
np.unique_values(data['YearsExperience'])

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.7,  3.9,  4. ,
        4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,  7.9,  8.2,
        8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

#Part 2

In [13]:
toyota_data=pd.read_csv(r"C:\Users\anchsingh\Anchal Singh\Data Analysis with Python\Toyota.csv")

In [14]:
toyota_data.head(4)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165

In [15]:
#index_col - first column as index
toyota_data=pd.read_csv(r"C:\Users\anchsingh\Anchal Singh\Data Analysis with Python\Toyota.csv", index_col=0,na_values=["??","????"])

In [16]:
toyota_data.head(4)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165

In [17]:
toyota_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   str
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   str
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), str(2)
memory usage: 112.3 KB

In [18]:
#Converting variable’s data types
#astype() method is used to explicitly convert data types from one to another

toyota_data['MetColor']=toyota_data['MetColor'].astype('object')
toyota_data['Automatic']=toyota_data['Automatic'].astype('object')

In [19]:
toyota_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   str
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   object
 6   Automatic  1436 non-null   object
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   str
 9   Weight     1436 non-null   int64
dtypes: float64(3), int64(3), object(2), str(2)
memory usage: 112.3+ KB

In [20]:
#category vs object data type

#nbytes() is used to get the total bytes consumed by the elements of the columns

toyota_data['FuelType'].nbytes

11488

In [21]:
toyota_data['FuelType'].astype('category').nbytes

1460

In [22]:
toyota_data['FuelType']=toyota_data['FuelType'].astype('category')

In [23]:
toyota_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   category
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   object
 6   Automatic  1436 non-null   object
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   str
 9   Weight     1436 non-null   int64
dtypes: category(1), float64(3), int64(3), object(2), str(1)
memory usage: 102.5+ KB

In [24]:
#cleaning column 'Doors'

print(np.unique(toyota_data['Doors']))

['2' '3' '4' '5' 'five' 'four' 'three']

In [25]:
#replace

toyota_data['Doors']=toyota_data['Doors'].replace({
    'three':'3',
    'four':'4',
    'five':'5'})

In [26]:
print(np.unique(toyota_data['Doors']))

['2' '3' '4' '5']

In [27]:
#Converting ‘Doors’ data type to int

toyota_data['Doors']=toyota_data['Doors'].astype('int64')

In [28]:
print(np.unique(toyota_data['Doors']))

[2 3 4 5]

In [29]:
toyota_data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,3,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.0,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [30]:
# toyota_data['Doors']=np.where(toyota_data['Doors'] is 3,toyota_data['Doors'],0)

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
C:\Users\anchsingh\AppData\Local\Temp\ipykernel_18396\2578146800.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  toyota_data['Doors']=np.where(toyota_data['Doors'] is 3,toyota_data['Doors'],0)

In [31]:
toyota_data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,0,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,0,1165
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,0,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,0,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,0,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,0,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,0,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,0,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,0,1015
1435,6950,76.0,1.0,Petrol,110.0,0.0,0,1600,0,1114

In [32]:
toyota_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   category
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   object
 6   Automatic  1436 non-null   object
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   int64
 9   Weight     1436 non-null   int64
dtypes: category(1), float64(3), int64(4), object(2)
memory usage: 102.5+ KB

In [33]:
#converting Fuel Type column into object datatype

toyota_data['FuelType']=toyota_data['FuelType'].astype('object')

In [34]:
#Filling missing values with 0

toyota_data['FuelType']=toyota_data['FuelType'].fillna(0)

In [40]:
#Checking missing values in each columns

toyota_data.isnull().sum()

Price          0
Age          100
KM            15
FuelType       0
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64